name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # ou a versão que você preferir

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          private_key: ${{ secrets.private_key }}
          client_email: ${{ secrets.client_email }}
          client_id: ${{ secrets.client_id }}
          auth_uri: ${{ secrets.auth_uri }}
          token_uri: ${{ secrets.token_uri }}
          auth_provider_x509_cert_url: ${{ secrets.auth_provider_x509_cert_url }}
          client_x509_cert_url: ${{ secrets.client_x509_cert_url }}
          universe_domain: ${{ secrets.universe_domain }}
        run: node seu_script.js
