name: CI

on: 
  push:
    branches:
      - main  # ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # ou a versão que você está usando

      - name: Install dependencies
        run: npm install

      - name: Run your script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          node your-script.js  # Substitua pelo nome do seu arquivo de script
